In [6]:
#one hot encodding
from sklearn.preprocessing import OneHotEncoder
s1="she is good girl"
s2="he is good boy"
s3="both are good "
data= pd.DataFrame(
    {
   "sentence": [s1,s2,s3]
    }
)


enc=data["sentence"].str.get_dummies(sep=' ')
enc 
# import numpy as np

# # Sample categorical data
# data = np.array([
#     ['Red'],
#     ['Green'],
#     ['Blue'],
#     ['Red']
# ])

# # Create OneHotEncoder instance
# encoder = OneHotEncoder(sparse_output=False)  # sparse_output=False returns a NumPy array

# # Fit and transform the data
# encoded_array = encoder.fit_transform(data)

# # Get feature names
# feature_names = encoder.get_feature_names_out(['Color'])

# print("Encoded Array:\n", encoded_array)
# print("Feature Names:", feature_names)


are  both  boy  girl  good  he  is  she
0    0     0    0     1     1   0   1    1
1    0     0    1     0     1   1   1    0
2    1     1    0     0     1   0   0    0

In [13]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
data=pd.DataFrame({
    "documents":["the food is good","the food is bad","the food is not good"]
})

data["documents"].str.get_dummies(sep=" ")

bad  food  good  is  not  the
0    0     1     1   1    0    1
1    1     1     0   1    0    1
2    0     1     1   1    1    1

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "he is  good boy",
    "she is good girl",
    "boy and girl are good"
]
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", X.toarray())


Vocabulary: ['boy' 'girl' 'good']
BoW Matrix:
 [[1 0 1]
 [0 1 1]
 [1 1 1]]


In [28]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "the food is good",
    "the food is bad"
]

# Bigram BoW
vectorizer = CountVectorizer(max_features=100,binary =True ,ngram_range=(1,2),stop_words="english")
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", X.toarray())


Vocabulary: ['bad' 'food' 'food bad' 'food good' 'good']
BoW Matrix:
 [[0 1 0 1 1]
 [1 1 1 0 0]]


In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentences = [
    "good girl female",
    "good boy male",
    "boy girl good"
]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF Matrix:\n", X.toarray())


Vocabulary: ['boy' 'female' 'girl' 'good' 'male']
TF-IDF Matrix:
 [[0.         0.72033345 0.54783215 0.42544054 0.        ]
 [0.54783215 0.         0.         0.42544054 0.72033345]
 [0.61980538 0.         0.61980538 0.48133417 0.        ]]
